### ISSUE TITLE
Code Review: Handle corrupt replays

### ISSUE THREAD

**Issue by Askaholic** [FAForever/faf-scfa-replay-parser#2]
https://github.com/FAForever/faf-scfa-replay-parser/blob/28e104325090037ede31febbb95cd21c83207d82/replay_parser/reader.py#L108

What if `self.buffer` reaches EOF? Right now it will return `b""` and your code will raise an exception somewhere down the line. I think it would be better if you raise `EOFError` here or make an exception like `CorruptReplayException` and raise it.

You should also call `self.read()` instead of `self.buffer.read()` everywhere else in the reader so that functions like `read_string`, `read_byte`, `peek_byte`, etc. will also raise `EOFError` or `CorruptReplayException` if the expected data doesn't exist

**Comment by Askaholic** [comment]
https://github.com/FAForever/faf-scfa-replay-parser/blob/28e104325090037ede31febbb95cd21c83207d82/replay_parser/reader.py#L36

What if you get `UnicodeDecodeError`?

**Comment by norraxx** [comment]
1) I'm not sure, if we have to raise. When such situation happens? Like from my point of view: in current situation algorithm per each command checks the size of buffer and reads it.
And there is situation, when we shouldn't rise exceptions, it's when there is continuous stream that you're trying to read and parse, like replay server has. If there information won't be complete, it's fine, we can behave quiet.
2) If such situation happens, then we're out of `unicode` and donno if we should continue.

**Comment by Askaholic** [comment]
Yea, basically there isn't any error handling for parsing corrupt replay data. If you pass it bad data, the reader will just crash on some random exception somewhere. It would be nicer if there was a `ParseError` that you could catch and handle when calling the replay parser from another project.

**Comment by norraxx** [comment]
I'll add some common exception, when we'll get problem with data inside.
