### ISSUE TITLE
Random seed probably uint and not float

### ISSUE THREAD

**Issue by Askaholic** [FAForever/faf-scfa-replay-parser#7]
Crotalus parser:
https://github.com/Crotalus/ReplayParser/blob/86af322057fa4eae5b744213988abfcc1e49bf48/Replay/ReplayHeader.cs#L57

And same in JavaScript parser:
https://fafafaf.bitbucket.io/js/replayParser.js

**Comment by norraxx** [comment]
Check every command that is here: https://github.com/FAForever/faf-scfa-replay-parser/blob/master/replay_parser/constants.py as `uint`
