### ISSUE TITLE
It may make sense to upstream your spec into https://github.com/kaitai-io/kaitai_struct_formats/

### ISSUE THREAD

**Issue by KOLANICH** [FAForever/faf-scfa-replay-parser#9]
Also you may find useful https://github.com/kaitaiStructCompile/kaitaiStructCompile.py

**Comment by norraxx** [comment]
I'm not sure, what's needed or what do you want from me? :-)
I suppose there is already kaitai file, where replay structure is defined. If you want to publish this kaitai, go ahead :-)
